/**
 * SMART VILLA STUDY - DATA ENGINE
 * قاعدة البيانات الشاملة للدراسة الهندسية والتقنية للفيلا الذكية
 * جميع البيانات مهيأة محلياً وتعمل بدون أي اتصال خارجي أو Backend
 */

const VILLA_SPECS = {
    title: "SMART VILLA",
    subtitle: "Interactive Smart Home & IoT Infrastructure Engineering Study",
    arabicTitle: "دراسة هندسية وتقنية متكاملة للفيلا الذكية وبنية إنترنت الأشياء",
    projectType: "Residential Luxury Smart Villa (فيلا سكنية ذكية)",
    scope: "Architectural 3D + IoT Engineering + Electrical & Network Infrastructure + Automation Scenarios",
    plotArea: "650 m²",
    builtUpArea: "520 m²",
    floorsCount: 2,
    roomsCount: 14,
    totalDevices: 82,
    sensorsCount: 24,
    camerasCount: 8,
    networkDrops: 16,
    accessPointsCount: 4,
    rackUnits: "12U Central Enclosure",
    summary: "دراسة متكاملة لتجهيز فيلا سكنية حديثة ببنية تحتية رقمية ذكية تعتمد أسلوب الأتمتة المحلية (Local Edge Intelligence) مع تكامل شامل بين الإضاءة، التكييف، الأمان، كشف المخاطر، والشبكات عالية الاعتمادية وفق أفضل الممارسات الهندسية."
};

const ROOMS_DATA = [
    {
        id: "entrance",
        name: "المدخل الرئيسي والموزع",
        nameEn: "Main Entrance & Foyer",
        floor: "ground",
        floorName: "الطابق الأرضي",
        area: "24 m²",
        dimensions: "6.0m x 4.0m",
        description: "واجهة استقبال الزوار ونقطة الدخول الرئيسية، مجهزة بنظام قفل بيومتري ذكي، جرس مرئي ذكي، حساس حركة للأتمتة الترحيبية، وإضاءة متكيفة.",
        deviceCount: 6,
        wiringNotes: "مواسير PVC 25mm مخصصة لكابلات Cat6A المتجهة للجرس والكاميرا الخارجية، وتغذية 220V للقفل والمفتاح الذكي بعلبة 86-type بعمق 50mm.",
        scenarios: ["Welcome Home", "Guest Arrival", "Night Security"],
        cameraPos: { x: 0, y: 3.5, z: 12 },
        targetPos: { x: 0, y: 1.2, z: 5.5 }
    },
    {
        id: "living",
        name: "صالة المعيشة العائلية",
        nameEn: "Family Living Room",
        floor: "ground",
        floorName: "الطابق الأرضي",
        area: "42 m²",
        dimensions: "7.0m x 6.0m",
        description: "الفراغ الرئيسي للراحة العائلية، يتميز بإضاءة محيطية مخفية وقابلة للتعتيم (Dimmers)، تحكم ذكي بالستائر والتكييف، وحساس مناخ متطور ومكنسة روبوتية.",
        deviceCount: 9,
        wiringNotes: "مسارات Cat6A لنقطة الشاشة الذكية ووحدة الترفيه، وخطوط تحكم للمحركات الكهربائية للستائر 220V مع سلك محايد (Neutral).",
        scenarios: ["Cinema Mode", "Family Relax", "All-Off Bedtime"],
        cameraPos: { x: -4.5, y: 4.5, z: 6.5 },
        targetPos: { x: -3.0, y: 1.5, z: 1.0 }
    },
    {
        id: "majlis",
        name: "مجلس الضيوف الفاخر",
        nameEn: "Luxury Guest Majlis",
        floor: "ground",
        floorName: "الطابق الأرضي",
        area: "48 m²",
        dimensions: "8.0m x 6.0m",
        description: "فراغ الضيافة الرسمي ذو الطابع المعماري الأنيق، مزود بمشاهد إضاءة ضيافة متعددة القنوات (Scene Controller)، تحكم ذكي دقيق بدرجة الحرارة، ومستشعرات جودة هواء.",
        deviceCount: 8,
        wiringNotes: "علب مفاتيح عميقة 50mm لدعم وحدات التحكم بالمشاهد المتعددة، مع تغذية مستقلة لمكيفات الهواء المخفية (Concealed FCU).",
        scenarios: ["Majlis Hospitality", "Evening Ambience", "Eco Standby"],
        cameraPos: { x: 5.5, y: 4.5, z: 6.5 },
        targetPos: { x: 4.0, y: 1.5, z: 1.0 }
    },
    {
        id: "dining",
        name: "غرفة الطعام الرسمية",
        nameEn: "Formal Dining Room",
        floor: "ground",
        floorName: "الطابق الأرضي",
        area: "28 m²",
        dimensions: "5.6m x 5.0m",
        description: "مساحة متصلة بالمجلس والمطبخ، مجهزة بإضاءة ثريا قابلة للتعتيم مع تحكم بالمشاهد المرتبطة بوجبات الطعام والضيافة ومستشعر حركة ذكي.",
        deviceCount: 5,
        wiringNotes: "خطوط تعتيم دايلاك/مرحل ذكي باللوحة الفرعية للثريا مع مسار أنيق بمواسير 20mm.",
        scenarios: ["Dinner Scene", "Bright Cleaning", "Standby"],
        cameraPos: { x: 3.5, y: 4.0, z: -1.0 },
        targetPos: { x: 3.0, y: 1.5, z: -3.5 }
    },
    {
        id: "kitchen",
        name: "المطبخ الذكي ومنطقة الخدمات",
        nameEn: "Smart Kitchen & Prep Area",
        floor: "ground",
        floorName: "الطابق الأرضي",
        area: "30 m²",
        dimensions: "6.0m x 5.0m",
        description: "عصب الأجهزة الذكية والأمان، مزود بثلاجة ذكية متصلة، حساس غاز ودخان، حساس تسرب مياه مع محبس إغلاق تلقائي، وأجهزة طهي ذكية.",
        deviceCount: 10,
        wiringNotes: "محبس كهرومغناطيسي على خط المياه الرئيسي بجهد 12V DC، حساسات دخان وغاز بأسلاك تغذية دائمة، ومسارات Cat6A للأجهزة الكبيرة.",
        scenarios: ["Kitchen Safety", "Cooking Prep", "Night Guard"],
        cameraPos: { x: -3.5, y: 4.0, z: -1.0 },
        targetPos: { x: -3.5, y: 1.5, z: -4.0 }
    },
    {
        id: "tech_room",
        name: "غرفة التقنية وكابينة السيرفر (Rack)",
        nameEn: "Central Tech & Network Room",
        floor: "ground",
        floorName: "الطابق الأرضي",
        area: "10 m²",
        dimensions: "3.5m x 2.8m",
        description: "القلب النابض لشبكة وأنظمة المنزل الذكي، تحتوي على كابينة خوادم 19 بوصة 12U، محول PoE مُدار، جهاز التخزين NVR، وحدة الـ Hub المحلية، وUPS للطوارئ.",
        deviceCount: 8,
        wiringNotes: "نقطة التقاء جميع مواسير الداتا 25mm/32mm من كافة أرجاء الفيلا، خط أرضي نحاسي معزول (Dedicated Clean Grounding) وتغذية AC عبر قاطع مخصص 20A مع UPS.",
        scenarios: ["Continuous Monitoring", "Fail-safe Power", "Thermal Overheat Alert"],
        cameraPos: { x: -1.0, y: 3.0, z: -3.0 },
        targetPos: { x: -1.0, y: 1.5, z: -5.5 }
    },
    {
        id: "garage",
        name: "المرآب وبوابة السيارات الذكية",
        nameEn: "Smart Garage & EV Charging",
        floor: "ground",
        floorName: "الطابق الأرضي",
        area: "36 m²",
        dimensions: "6.0m x 6.0m",
        description: "مرآب يتسع لسيارتين مع باب كهربائي أوتوماتيكي ذكي، كاميرا مراقبة بدقة 4K مع تمييز المركبات، ومستشعر حركة خارجي.",
        deviceCount: 5,
        wiringNotes: "تغذية 3-Phase 32A لشاحن المركبة الكهربائية EV مع كابل Cat6A لوحدة تحكم الشاحن والمراقبة.",
        scenarios: ["Car Arrival", "Garage Door Left Open Alert", "Perimeter Guard"],
        cameraPos: { x: -8.5, y: 4.5, z: 8.5 },
        targetPos: { x: -6.0, y: 1.5, z: 4.5 }
    },
    {
        id: "garden",
        name: "الحديقة والمساحات الخارجية",
        nameEn: "Outdoor Landscape & Patio",
        floor: "outdoor",
        floorName: "المساحات الخارجية",
        area: "180 m²",
        dimensions: "محيط الفيلا",
        description: "مناطق خارجية خضراء وجلسة عائلية، مزودة بإضاءة واجهات ذكية (Landscape RGBW)، محطة ري ذكية متصلة بالأرصاد الجوية، وحماية محيطية بالكاميرات.",
        deviceCount: 7,
        wiringNotes: "كابلات مسلحة خارجية مخصصة للدفن المباشر في مواسير PVC معزولة ضد الرطوبة IP67 ومحولات 24V DC لمحابس الري.",
        scenarios: ["Sunset Illumination", "Weather-Adaptive Irrigation", "Perimeter Alert"],
        cameraPos: { x: 0, y: 12.0, z: 18.0 },
        targetPos: { x: 0, y: 0.0, z: 0.0 }
    },
    {
        id: "master_bed",
        name: "جناح النوم الرئيسي",
        nameEn: "Master Bedroom Suite",
        floor: "first",
        floorName: "الطابق الأول",
        area: "40 m²",
        dimensions: "7.0m x 5.7m",
        description: "جناح الراحة الملكي، مجهز بمفتاح بجانب السرير للتحكم الكامل بجميع أنظمة الفيلا (Master All-Off)، تحكم تلقائي بستائر النوافذ، وتكييف هادئ بحساس حضور دقيق.",
        deviceCount: 8,
        wiringNotes: "مفاتيح ذكية متعددة الاتجاهات (Multi-way scene switch) بجانب جانبي السرير، مع أسلاك إشارة منخفضة الجهد لمحركات الستائر.",
        scenarios: ["Good Morning", "Deep Sleep Mode", "Night Bathroom Walkway"],
        cameraPos: { x: -4.5, y: 7.5, z: 5.5 },
        targetPos: { x: -3.0, y: 4.5, z: 1.0 }
    },
    {
        id: "master_bath",
        name: "الحمام الرئيسي الفاخر",
        nameEn: "Master En-suite Bathroom",
        floor: "first",
        floorName: "الطابق الأول",
        area: "16 m²",
        dimensions: "4.0m x 4.0m",
        description: "مساحة متصلة بالجناح الرئيسي، تتميز بإضاءة أرضية خافتة تلقائية ليلًا، مرآة ذكية، حساس رطوبة لتشغيل مروحة الشفط تلقائيًا، وحساس تسرب مياه.",
        deviceCount: 5,
        wiringNotes: "مفاتيح معزولة بحماية ضد الرطوبة وتغذية مروحة الشفط عبر مرحل ذكي متصل بحساس الرطوبة.",
        scenarios: ["Auto Dehumidify", "Midnight Gentle Glow"],
        cameraPos: { x: -5.5, y: 7.0, z: -1.5 },
        targetPos: { x: -4.0, y: 4.5, z: -3.5 }
    },
    {
        id: "office",
        name: "المكتب المنزلي وغرفة العمل",
        nameEn: "Home Office & Study",
        floor: "first",
        floorName: "الطابق الأول",
        area: "22 m²",
        dimensions: "5.0m x 4.4m",
        description: "بيئة عمل هادئة وعالية الإنتاجية، مزودة بنقطتي شبكة Cat6A فائق السرعة، إضاءة مكتبية بيضاء متكيفة مع ساعات اليوم (Circadian Rhythm)، وتحكم مستقل بالمناخ.",
        deviceCount: 6,
        wiringNotes: "نقطتي شبكة مزدوجة RJ45 متصلة باللوحة الرئيسية مباشرة Cat6A لضمان سرعات 10Gbps بدون أي تشويش.",
        scenarios: ["Focus Work Mode", "Video Conference", "Eco Standby"],
        cameraPos: { x: 4.5, y: 7.5, z: 5.5 },
        targetPos: { x: 3.5, y: 4.5, z: 2.0 }
    },
    {
        id: "family_hall",
        name: "الصالة العلوية والموزع",
        nameEn: "First Floor Family Hall",
        floor: "first",
        floorName: "الطابق الأول",
        area: "30 m²",
        dimensions: "6.0m x 5.0m",
        description: "مساحة توزيع وتجمع أفراد العائلة بالطابق الأول، متصلة بنقطة وصول Wi-Fi 6 سقفية لتغطية كامل الطابق، وحساس حركة لأتمتة الإنارة الليلية.",
        deviceCount: 5,
        wiringNotes: "نقطة سقفية لكابل Cat6A PoE لتغذية نقطة الوصول Wi-Fi 6 مباشرة من الموزع المركزي.",
        scenarios: ["Family Evening", "Gentle Night Hallway"],
        cameraPos: { x: 0, y: 8.0, z: 2.0 },
        targetPos: { x: 0, y: 4.5, z: 0.0 }
    },
    {
        id: "bedroom2",
        name: "غرفة النوم الثانية",
        nameEn: "Bedroom 2 (Guest / Kids)",
        floor: "first",
        floorName: "الطابق الأول",
        area: "24 m²",
        dimensions: "5.0m x 4.8m",
        description: "غرفة نوم مجهزة بمفتاح ذكي ثنائي، حساس مناخ، تحكم تكييف ذكي، ونقطة شبكة متصلة بالمكتب الشخصي.",
        deviceCount: 4,
        wiringNotes: "علب مفاتيح مع سلك محايد (Neutral) ونقطة داتا Cat6A.",
        scenarios: ["Study Time", "Sleep Time"],
        cameraPos: { x: 4.5, y: 7.5, z: -2.0 },
        targetPos: { x: 3.5, y: 4.5, z: -4.0 }
    },
    {
        id: "bedroom3",
        name: "غرفة النوم الثالثة",
        nameEn: "Bedroom 3",
        floor: "first",
        floorName: "الطابق الأول",
        area: "22 m²",
        dimensions: "4.8m x 4.5m",
        description: "غرفة نوم إضافية مجهزة بنظام تحكم بالإضاءة والتكييف وحساس حركة للممر الخاص بها.",
        deviceCount: 4,
        wiringNotes: "تمديد تكييف ذكي ونقطة إضاءة LED متوافقة مع التعتيم.",
        scenarios: ["Bedtime", "Morning Wakeup"],
        cameraPos: { x: -1.0, y: 7.5, z: -2.5 },
        targetPos: { x: -1.0, y: 4.5, z: -4.5 }
    }
];

const DEVICE_CATEGORIES = [
    { id: "lighting", name: "أنظمة الإضاءة الذكية", nameEn: "Smart Lighting", icon: "💡", count: 26 },
    { id: "sensors", name: "الحساسات ومستشعرات البيئة", nameEn: "Sensors & Environment", icon: "📡", count: 24 },
    { id: "security", name: "الأمن والمراقبة والتحكم بالدخول", nameEn: "Security & Access", icon: "🛡️", count: 14 },
    { id: "hvac", name: "التكييف والتحكم بالمناخ", nameEn: "HVAC Climate Control", icon: "❄️", count: 7 },
    { id: "network", name: "البنية الشبكية والاتصالات", nameEn: "Network Infrastructure", icon: "🌐", count: 12 },
    { id: "automation", name: "وحدات المعالجة والمتحكمات", nameEn: "Gateways & Hubs", icon: "⚙️", count: 4 },
    { id: "appliances", name: "الأجهزة المنزلية الذكية", nameEn: "Smart Appliances", icon: "🔌", count: 5 }
];

const DEVICES_DATA = [
    // --- LIGHTING ---
    {
        id: "light_entrance_main",
        name: "مفتاح إضاءة ذكي مزدوج - المدخل",
        nameEn: "Smart 2-Gang Switch - Entrance",
        category: "lighting",
        room: "entrance",
        roomName: "المدخل الرئيسي",
        status: "on",
        brightness: 90,
        power: "220V AC with Neutral",
        communication: "Zigbee 3.0 / Matter",
        installation: "Wall Mount (120cm AFFL) 86-type box",
        wiring: "3x1.5mm² Cu Wire + Neutral in 20mm PVC Conduit",
        purpose: "التحكم في إنارة الممر والمصابيح الترحيبية المعلقة مع دعم تشغيل المشاهد التلقائية فور دخول الباب.",
        technicalSpecs: "Max Load: 600W/gang, Capacitive Touch, Zero-Cross Detection, Local Memory.",
        pos3d: { x: 0.8, y: 1.2, z: 4.8 }
    },
    {
        id: "light_living_dimmer",
        name: "مخفت إضاءة ذكي للصالون",
        nameEn: "Smart Dimmer Controller - Living Room",
        category: "lighting",
        room: "living",
        roomName: "صالة المعيشة",
        status: "on",
        brightness: 75,
        power: "220V AC with Neutral",
        communication: "Matter over Thread",
        installation: "In-Wall Deep Junction Box (50mm)",
        wiring: "Leading/Trailing Edge Phase Cut, 20mm Conduit",
        purpose: "تعديل مستويات الإضاءة تدريجيًا لمشاهد الاسترخاء العائلي والسينما دون أي وميض (Flicker-free).",
        technicalSpecs: "Dimming Range: 1-100%, Trailing-Edge Triac, Overheating Protection.",
        pos3d: { x: -2.0, y: 1.2, z: 2.5 }
    },
    {
        id: "light_living_ceiling",
        name: "إضاءة سقفية دائرية LED ذكية",
        nameEn: "Smart LED Downlight Array - Living Room",
        category: "lighting",
        room: "living",
        roomName: "صالة المعيشة",
        status: "on",
        brightness: 80,
        power: "220V AC Constant Current Driver",
        communication: "Zigbee 3.0 via Dimmer",
        installation: "Ceiling Recessed (Gypsum Ceiling)",
        wiring: "Low-voltage 24V from Central LED Driver in Ceiling",
        purpose: "إضاءة الغرفة الأساسية مع ضبط درجة حرارة اللون (CCT: 2700K - 6500K) وفق إيقاع اليوم الطبيعي.",
        technicalSpecs: "15W per fixture, 1200 Lumens, CRI > 95, Dimmable to 1%.",
        pos3d: { x: -3.0, y: 2.8, z: 1.0 }
    },
    {
        id: "light_majlis_chandelier",
        name: "مرحل ذكي لثريا المجلس الفاخرة",
        nameEn: "Smart Relay Module - Majlis Chandelier",
        category: "lighting",
        room: "majlis",
        roomName: "المجلس الفاخر",
        status: "off",
        brightness: 0,
        power: "220V AC 16A High-Inrush Relay",
        communication: "Zigbee 3.0 Mesh",
        installation: "Ceiling Concealed / Electrical Panel Relay",
        wiring: "3x2.5mm² Dedicated Circuit from SMDB",
        purpose: "تشغيل وحماية دوائر الإضاءة الثقيلة للثريا الكريستالية في المجلس وربطها بمشهد الضيافة.",
        technicalSpecs: "16A Dry Contact Relay, 100A Inrush Current Tolerant, Power Metering.",
        pos3d: { x: 4.0, y: 2.8, z: 1.0 }
    },
    {
        id: "light_kitchen_strip",
        name: "شريط LED ذكي لأسطح المطبخ (Under-Cabinet)",
        nameEn: "Smart Under-Cabinet LED Strip - Kitchen",
        category: "lighting",
        room: "kitchen",
        roomName: "المطبخ الذكي",
        status: "on",
        brightness: 100,
        power: "24V DC via 60W Ultra-slim Power Supply",
        communication: "Zigbee 3.0 / Local PWM Driver",
        installation: "Under kitchen upper cabinets in aluminum profile",
        wiring: "2x1.0mm² Low Voltage DC from cabinet driver",
        purpose: "إضاءة عمل عالية السطوع لأسطح التحضير والطهي تعمل تلقائيًا عند استشعار الحركة.",
        technicalSpecs: "COB LED 24V, 4000K Neutral White, CRI 92, High Heat Dissipation.",
        pos3d: { x: -3.5, y: 1.6, z: -4.5 }
    },
    {
        id: "light_master_bed",
        name: "لوحة مفاتيح المشاهد الرئيسية - غرفة الماستر",
        nameEn: "Master Suite 4-Scene Controller",
        category: "lighting",
        room: "master_bed",
        roomName: "جناح النوم الرئيسي",
        status: "on",
        brightness: 40,
        power: "220V AC or Low Voltage Bus",
        communication: "Matter over Thread",
        installation: "Bedside Wall Mount (65cm AFFL)",
        wiring: "Multi-core Low Voltage or Standard 220V + Neutral",
        purpose: "مفتاح مركزي بجانب السرير لإطفاء كامل الفيلا بلمسة واحدة (All-Off)، أو تشغيل وضع القراءة والنوم.",
        technicalSpecs: "4 Programmable Buttons with LED Backlight Feedback, Local Scene Storage.",
        pos3d: { x: -4.5, y: 1.0, z: 1.5 }
    },

    // --- SENSORS ---
    {
        id: "sensor_entrance_motion",
        name: "حساس حركة ووجود بشري عالي الدقة (mmWave)",
        nameEn: "PIR + mmWave Human Presence Sensor - Entrance",
        category: "sensors",
        room: "entrance",
        roomName: "المدخل الرئيسي",
        status: "normal",
        stateValue: "Clear (No motion)",
        power: "5V USB / Direct 220V Concealed Module",
        communication: "Zigbee 3.0",
        installation: "Ceiling Center Recessed (2.8m AFFL)",
        wiring: "2x0.75mm² DC from ceiling transformer",
        purpose: "كشف وجود الأشخاص بدقة متناهية حتى أثناء السكون التام لتشغيل إضاءة المدخل والتكييف الترحيبي.",
        technicalSpecs: "24GHz Radar + Passive Infrared, Detection Angle 120°, Range 6 meters.",
        pos3d: { x: 0.0, y: 2.8, z: 4.5 }
    },
    {
        id: "sensor_kitchen_smoke",
        name: "حساس دخان وحرارة كهروضوئي معتمد",
        nameEn: "Photoelectric Smoke & Heat Detector - Kitchen",
        category: "sensors",
        room: "kitchen",
        roomName: "المطبخ الذكي",
        status: "normal",
        stateValue: "Normal (0.0% obscuration)",
        power: "Dual: 10-Year Lithium Battery + Hardwired Interconnect",
        communication: "Zigbee 3.0 / Dedicated 433MHz Interlink",
        installation: "Ceiling Mount, 1.5m away from cooking appliances",
        wiring: "Dedicated Interlink Cable to Alarm Buzzer / Dry contact to Hub",
        purpose: "الكشف المبكر عن أي أدخنة أو ارتفاع غير معتاد في درجات الحرارة وإطلاق محاكاة الطوارئ فورًا.",
        technicalSpecs: "EN 14604 Certified, Built-in 85dB Siren, Self-testing Chamber.",
        pos3d: { x: -3.5, y: 2.8, z: -3.5 }
    },
    {
        id: "sensor_kitchen_water",
        name: "حساس تسرب مياه مع محبس إغلاق أوتوماتيكي",
        nameEn: "Smart Water Leak Sensor & Shutoff Valve",
        category: "sensors",
        room: "kitchen",
        roomName: "المطبخ الذكي",
        status: "normal",
        stateValue: "Dry",
        power: "CR2450 Battery (Sensor) + 12V DC Adapter (Valve Actuator)",
        communication: "Zigbee 3.0 Local Direct Binding to Valve",
        installation: "Floor Base under Sink & Dishwasher + Inline Pipe Valve",
        wiring: "Low-voltage 2-core wire to motorized ball valve on cold water supply",
        purpose: "حماية الفيلا من أضرار الغرق عبر إغلاق خط المياه فور لمس قطرات الماء للمجسات الأرضية.",
        technicalSpecs: "IP67 Waterproof, Gold-plated Sensing Probes, Valve Motor Torque 40kgf.cm.",
        pos3d: { x: -4.2, y: 0.1, z: -5.0 }
    },
    {
        id: "sensor_kitchen_gas",
        name: "حساس كشف تسرب الغاز (LPG / Methane)",
        nameEn: "Combustible Gas Detector - Kitchen",
        category: "sensors",
        room: "kitchen",
        roomName: "المطبخ الذكي",
        status: "normal",
        stateValue: "Normal (0% LEL)",
        power: "220V AC Direct Plugin / Wall Box",
        communication: "Zigbee 3.0 / Dry Contact Output to Exhaust Fan",
        installation: "Wall Mount (30cm from floor for LPG / 30cm from ceiling for NG)",
        wiring: "220V AC Power + Dry Contact relay wire to kitchen exhaust hood",
        purpose: "استشعار تسرب الغاز وتشغيل شفاط الطوارئ وقطع الغاز تلقائيًا.",
        technicalSpecs: "Catalytic Combustion Sensor, Alarm threshold 8% LEL, 80dB Alarm.",
        pos3d: { x: -2.2, y: 0.8, z: -4.8 }
    },
    {
        id: "sensor_majlis_climate",
        name: "مستشعر مناخي متعدد (حرارة، رطوبة، جودة هواء CO2)",
        nameEn: "Multi-Sensor (Temp, Humidity, CO2, TVOC) - Majlis",
        category: "sensors",
        room: "majlis",
        roomName: "المجلس الفاخر",
        status: "normal",
        stateValue: "Temp: 22.5°C | Hum: 45% | CO2: 520 ppm",
        power: "Type-C 5V DC Continuous / Battery Backup",
        communication: "Matter over Thread",
        installation: "Wall Mount (150cm AFFL) away from direct sun and AC vents",
        wiring: "Micro USB / 5V DC line in 20mm conduit",
        purpose: "مراقبة راحة الضيوف وتشغيل التكييف وتنقية الهواء تلقائيًا عند ارتفاع نسبة ثاني أكسيد الكربون.",
        technicalSpecs: "NDIR CO2 Sensor, SHT40 Temp/Hum Sensor, Electronic Ink Display.",
        pos3d: { x: 5.5, y: 1.5, z: 2.0 }
    },
    {
        id: "sensor_door_entrance",
        name: "حساس مغناطيسي لحالة فتح/إغلاق الباب الرئيسي",
        nameEn: "Concealed Magnetic Door Contact - Entrance",
        category: "sensors",
        room: "entrance",
        roomName: "المدخل الرئيسي",
        status: "normal",
        stateValue: "Closed & Secure",
        power: "CR2032 Lithium Cell (5-Year Battery Life)",
        communication: "Zigbee 3.0",
        installation: "Concealed inside door frame and leaf",
        wiring: "No exposed wiring; wireless with ultra-low power sleep state",
        purpose: "معرفة حالة الباب لحظيًا، تشغيل إضاءة المدخل عند الفتح، وإطلاق إنذار عند الفتح غير المصرح به.",
        technicalSpecs: "Operating Gap: 15-25mm, Tamper Switch, Built-in Antenna.",
        pos3d: { x: 0.0, y: 1.2, z: 5.8 }
    },

    // --- SECURITY ---
    {
        id: "lock_entrance",
        name: "قفل ذكي بيومتري عالي الأمان للباب الرئيسي",
        nameEn: "Heavy-Duty Biometric Smart Lock - Entrance",
        category: "security",
        room: "entrance",
        roomName: "المدخل الرئيسي",
        status: "locked",
        stateValue: "Locked",
        power: "Rechargeable Lithium 4200mAh + 8x AA Backup + Type-C Emergency",
        communication: "Zigbee 3.0 / Matter",
        installation: "Mortise 6068 Multi-point Locking Mechanism",
        wiring: "Wireless + Optional 12V DC constant feed through door hinge conduit",
        purpose: "الدخول الآمن عبر بصمة الإصبع، بطاقة RFID، الرقم السري، وتفعيل مشاهد المنزل عند التعرف على المالك.",
        technicalSpecs: "Bank-grade 3D Fingerprint, C-Level Security Cylinder, Tamper Alarm.",
        pos3d: { x: 0.2, y: 1.1, z: 5.8 }
    },
    {
        id: "cam_entrance_doorbell",
        name: "جرس باب تفاعلي ذكي بكاميرا 2K وذكاء اصطناعي",
        nameEn: "AI 2K Video Doorbell - Main Entrance",
        category: "security",
        room: "entrance",
        roomName: "المدخل الرئيسي",
        status: "normal",
        stateValue: "Streaming 2K Ready",
        power: "16V-24V AC Hardwired from Doorbell Transformer",
        communication: "Wi-Fi 6 (5GHz/2.4GHz) / RTSP stream to NVR",
        installation: "Exterior Wall next to entrance door (140cm AFFL)",
        wiring: "2x1.0mm² Power Cable + Cat6A data backup in 20mm PVC conduit",
        purpose: "التحدث مع الزوار صوتيًا ومرئيًا عبر الشاشات الداخلية والهاتف وتسجيل المقاطع محليًا بالكامل.",
        technicalSpecs: "2K HDR Video, 160° Field of View, Color Night Vision, Local On-device Person/Package AI.",
        pos3d: { x: 0.9, y: 1.4, z: 5.9 }
    },
    {
        id: "cam_garden_perimeter",
        name: "كاميرا مراقبة خارجية 4K مع زاوية تغطية واسعة",
        nameEn: "4K PoE Outdoor AI Bullet Camera - Garden Perimeter",
        category: "security",
        room: "garden",
        roomName: "الحديقة الخارجية",
        status: "normal",
        stateValue: "Active Monitoring (4K 30fps)",
        power: "Power over Ethernet (PoE 802.3af - 8W)",
        communication: "Hardwired Cat6A Ethernet direct to PoE Switch",
        installation: "Corner Wall Bracket (3.5m AFFL) IP67 Waterproof",
        wiring: "Outdoor-rated Cat6A FTP shielded cable in UV-resistant conduit",
        purpose: "مراقبة السور الخارجي والحديقة مع تمييز المركبات والأشخاص وإرسال لقطات للمخزن المحلي NVR.",
        technicalSpecs: "Sony Starvis Sensor 8MP, 110° FOV, 30m IR Night Vision, IP67/IK10 Vandal-proof.",
        pos3d: { x: 6.0, y: 3.5, z: 6.0 }
    },
    {
        id: "cam_garage",
        name: "كاميرا مراقبة داخلية للمرآب بدقة 4K",
        nameEn: "4K PoE AI Turret Camera - Garage",
        category: "security",
        room: "garage",
        roomName: "المرآب الذكي",
        status: "normal",
        stateValue: "Active Guard",
        power: "PoE (802.3af - 6W)",
        communication: "Hardwired Cat6A to PoE Switch",
        installation: "Ceiling Corner Mount (3.0m AFFL)",
        wiring: "Cat6A UTP in 20mm PVC ceiling conduit",
        purpose: "مراقبة المركبات والبوابة الآلية للمرآب مع دعم إشعارات فتح الباب أثناء غياب أفراد المنزل.",
        technicalSpecs: "4K UHD, Built-in Mic, Smart Motion Detection, Local MicroSD + NVR Storage.",
        pos3d: { x: -5.5, y: 2.8, z: 5.5 }
    },
    {
        id: "siren_central_alarm",
        name: "صافرة إنذار داخلية وميضية 110dB",
        nameEn: "Central Strobe Alarm Siren - Tech Hallway",
        category: "security",
        room: "tech_room",
        roomName: "غرفة التقنية",
        status: "off",
        stateValue: "Standby",
        power: "12V DC Hardwired + Internal Rechargeable Battery",
        communication: "Zigbee 3.0 / Dry contact from Fire & Intrusion Hub",
        installation: "Wall Mount High Level (2.6m AFFL)",
        wiring: "2x1.5mm² Power cable from Central Security Panel",
        purpose: "إصدار تنبيه صوتي عالي النبرة وإضاءة وميضية حمراء عند كشف حريق أو تسرب غاز أو اقتحام أمني.",
        technicalSpecs: "110dB Acoustic Siren, High-intensity Red Xenon/LED Strobe, IP54 Housing.",
        pos3d: { x: -1.0, y: 2.6, z: -3.2 }
    },

    // --- HVAC ---
    {
        id: "thermostat_living",
        name: "منظم حرارة ذكي بشاشة زجاجية لمسية - الصالة",
        nameEn: "Smart Glass Touch Thermostat - Living Room",
        category: "hvac",
        room: "living",
        roomName: "صالة المعيشة",
        status: "on",
        targetTemp: 22,
        currentTemp: 22.5,
        mode: "cool",
        power: "24V AC Common Wire (C-Wire) or Modbus 12V",
        communication: "Zigbee 3.0 / Modbus RTU (Direct to AC Controller)",
        installation: "Wall Mount (140cm AFFL) away from direct drafts",
        wiring: "5-Core Thermostat Cable (R, C, Y, G, W) or 2-Core Twisted Shielded for Modbus",
        purpose: "التحكم الدقيق في التكييف المخفي وتعديل سرعة المروحة تلقائيًا لترشيد الطاقة وخفض الضجيج.",
        technicalSpecs: "OLED Touch Display, Proportional PID Control, Modbus RS485 Interface.",
        pos3d: { x: -1.5, y: 1.4, z: 2.0 }
    },
    {
        id: "thermostat_majlis",
        name: "منظم حرارة ذكي للمجلس",
        nameEn: "Smart Digital Thermostat - Majlis",
        category: "hvac",
        room: "majlis",
        roomName: "المجلس الفاخر",
        status: "off",
        targetTemp: 21,
        currentTemp: 24.0,
        mode: "eco",
        power: "24V AC C-Wire",
        communication: "Matter over Thread",
        installation: "Wall Mount (140cm AFFL)",
        wiring: "5-Core low voltage thermostat wiring in 20mm conduit",
        purpose: "تشغيل التكييف المسبق قبل موعد الضيافة والحفاظ على وضع التوفير ECO عند خلو الفراغ.",
        technicalSpecs: "Temperature Accuracy: ±0.3°C, 3-Speed Fan Control, Compressor Protection Delay.",
        pos3d: { x: 3.5, y: 1.4, z: 2.0 }
    },
    {
        id: "thermostat_master",
        name: "منظم حرارة ذكي لجناح النوم الرئيسي",
        nameEn: "Smart Thermostat - Master Suite",
        category: "hvac",
        room: "master_bed",
        roomName: "جناح النوم الرئيسي",
        status: "on",
        targetTemp: 21.5,
        currentTemp: 21.5,
        mode: "cool",
        power: "24V AC C-Wire",
        communication: "Zigbee 3.0",
        installation: "Wall Mount (140cm AFFL)",
        wiring: "5-core shielded cable to Concealed FCU unit in ceiling",
        purpose: "توفير مناخ نوم فائق الهدوء مع جدولة انخفاض الحرارة ليلًا وارتفاعها بلطف قبل الاستيقاظ.",
        technicalSpecs: "Night Silent Fan Algorithm, Dual Stage Cooling, Humidity Integration.",
        pos3d: { x: -2.5, y: 4.5, z: 2.0 }
    },

    // --- NETWORK ---
    {
        id: "net_rack_main",
        name: "كابينة الخوادم والشبكة المركزية (19\" 12U Enclosure)",
        nameEn: "Central 19-inch 12U Network Rack",
        category: "network",
        room: "tech_room",
        roomName: "غرفة التقنية",
        status: "normal",
        stateValue: "Operational (Online)",
        power: "220V AC via 2kVA Online Smart UPS with SNMP",
        communication: "Fiber Optics Uplink + 10Gbps SFP+ Backbone",
        installation: "Wall-mounted heavy duty rack with dual exhaust fans",
        wiring: "Terminates all 16 Cat6A drops into 24-Port Patch Panel Cat6A",
        purpose: "تجميع وإيواء جميع وحدات المعالجة والمحولات المركزية في بيئة مبردة وآمنة وغير مسموعة في المنزل.",
        technicalSpecs: "12U 600x600mm, Tempered Glass Door, PDU with Power Metering, Dual Brush Cable Entries.",
        pos3d: { x: -1.0, y: 1.6, z: -4.8 }
    },
    {
        id: "net_switch_poe",
        name: "موزع شبكة مُدار 24-Port Gigabit PoE+ (370W)",
        nameEn: "Managed 24-Port PoE+ Switch (370W Budget)",
        category: "network",
        room: "tech_room",
        roomName: "غرفة التقنية",
        status: "normal",
        stateValue: "Ports Active: 14 | PoE Budget: 68W Used",
        power: "Internal AC Power Supply (370W Max)",
        communication: "L2+ Managed (VLANs, QoS, IGMP Snooping, STP)",
        installation: "Mounted in Rack Unit U4",
        wiring: "Direct patch cords to 24-port patch panel",
        purpose: "تزويد الكاميرات ونقاط الوصول وبوابات الأتمتة بالطاقة والبيانات الفائقة السرعة عبر سلك إيثرنت واحد.",
        technicalSpecs: "24x 1Gbps PoE+ Ports (802.3at/af), 4x 10G SFP+ Uplinks, Switching Capacity: 128Gbps.",
        pos3d: { x: -1.0, y: 1.8, z: -4.7 }
    },
    {
        id: "net_ap_ground",
        name: "نقطة وصول لاسلكية سقفية Wi-Fi 6 - الطابق الأرضي",
        nameEn: "Ceiling Mount Wi-Fi 6 Access Point - Ground Floor",
        category: "network",
        room: "entrance",
        roomName: "المدخل والموزع",
        status: "normal",
        stateValue: "Connected (32 Clients)",
        power: "PoE (802.3af - 11W)",
        communication: "Wi-Fi 6 (802.11ax) Dual Band MIMO 4x4",
        installation: "Ceiling Center Flush Mount (Clean Aesthetics)",
        wiring: "Cat6A PoE drop direct to Rack Patch Panel",
        purpose: "تأمين تغطية إنترنت لاسلكية فائقة السرعة وشبكة منفصلة لأجهزة إنترنت الأشياء (IoT Dedicated SSID).",
        technicalSpecs: "Max Throughput: 3.0 Gbps, Seamless Roaming (802.11k/v/r), Multi-SSID VLAN Tagging.",
        pos3d: { x: 0.0, y: 2.85, z: 2.0 }
    },
    {
        id: "net_ap_first",
        name: "نقطة وصول لاسلكية سقفية Wi-Fi 6 - الطابق الأول",
        nameEn: "Ceiling Mount Wi-Fi 6 Access Point - First Floor",
        category: "network",
        room: "family_hall",
        roomName: "الصالة العلوية",
        status: "normal",
        stateValue: "Connected (24 Clients)",
        power: "PoE (802.3af - 11W)",
        communication: "Wi-Fi 6 (802.11ax) 4x4 MIMO",
        installation: "Ceiling Center Flush Mount",
        wiring: "Cat6A PoE drop to Rack",
        purpose: "تغطية غرف النوم والمكتب المنزلي باتصال فائق الاستقرار دون أي نقاط ميتة أو انقطاع أثناء الحركة.",
        technicalSpecs: "3000 Mbps Aggregate Speed, OFDMA, Beamforming, Zero-Handoff Roaming.",
        pos3d: { x: 0.0, y: 5.85, z: 0.0 }
    },
    {
        id: "net_nvr_storage",
        name: "وحدة تسجيل الفيديو الشبكي المركزية 8-Channel 4K NVR",
        nameEn: "8-Channel 4K Network Video Recorder (NVR)",
        category: "network",
        room: "tech_room",
        roomName: "غرفة التقنية",
        status: "normal",
        stateValue: "Recording (2x 6TB WD Purple - 45 Days)",
        power: "12V DC from Rack PDU",
        communication: "Gigabit Ethernet (VLAN 30 Isolated Security)",
        installation: "Rack Mounted Unit U6",
        wiring: "Cat6A Patch to PoE Switch (Surveillance VLAN)",
        purpose: "تسجيل وحفظ تسجيلات جميع الكاميرات على مدار 24 ساعة محليًا داخل الفيلا دون أي تسريب سحابي.",
        technicalSpecs: "H.265+ Compression, 80Mbps Bandwidth, RAID-1 Redundancy, Smart AI Playback.",
        pos3d: { x: -1.0, y: 1.4, z: -4.7 }
    },

    // --- AUTOMATION & HUBS ---
    {
        id: "hub_local_controller",
        name: "المعالج المركزي للأتمتة المحلية (Edge Smart Home Hub)",
        nameEn: "Local-First Edge Smart Automation Controller",
        category: "automation",
        room: "tech_room",
        roomName: "غرفة التقنية",
        status: "normal",
        stateValue: "CPU: 8% | RAM: 1.2GB | Local Engine: ACTIVE",
        power: "12V DC via UPS / PoE Powered",
        communication: "Gigabit LAN + Zigbee 3.0 + Thread Border Router + Matter",
        installation: "Rack Mounted / DIN-Rail Industrial Enclosure",
        wiring: "Direct Ethernet to Core Switch + High-gain external antennas on rack roof",
        purpose: "تشغيل جميع السيناريوهات والأتمتة محليًا بالكامل داخل الفيلا لضمان العمل التام حتى عند انقطاع الإنترنت بنسبة 100%.",
        technicalSpecs: "Quad-Core ARM, 4GB RAM, Local SQLite Event Database, Hardware Crypto-Engine, Home Assistant / Matter Core.",
        pos3d: { x: -1.0, y: 2.0, z: -4.7 }
    },

    // --- APPLIANCES ---
    {
        id: "appliance_fridge",
        name: "الثلاجة الذكية مع كاميرات داخلية ومراقبة المخزون",
        nameEn: "Smart Connected Refrigerator - Kitchen",
        category: "appliances",
        room: "kitchen",
        roomName: "المطبخ الذكي",
        status: "normal",
        stateValue: "Temp: 4.0°C | Food Level: 78% | Door: Closed",
        power: "220V Dedicated Inverter Circuit 16A",
        communication: "Wi-Fi 6 (IoT VLAN 20) / Matter Bridge",
        installation: "Built-in Kitchen Cabinetry",
        wiring: "Dedicated 3x2.5mm² Power Line from Kitchen SMDB",
        purpose: "مراقبة درجة الحرارة الداخلية، تنبيه عند انخفاض الأغذية، وتنبيه فوري إذا تُرك الباب مفتوحًا لأكثر من 60 ثانية.",
        technicalSpecs: "Twin Cooling Plus, Internal ViewInside Cameras, Linear Inverter Compressor, Energy Star Grade A+++.",
        pos3d: { x: -4.0, y: 1.2, z: -2.8 }
    },
    {
        id: "appliance_vacuum",
        name: "المكنسة الروبوتية الذكية مع محطة التفريغ التلقائي",
        nameEn: "Smart Robot Vacuum & Mop with Auto-Empty Dock",
        category: "appliances",
        room: "living",
        roomName: "صالة المعيشة",
        status: "normal",
        stateValue: "Battery: 85% | Dust Bin: 25% | Water Tank: 90% | Status: Docked",
        power: "220V AC Base Station Socket",
        communication: "Wi-Fi 6 (2.4GHz IoT Network)",
        installation: "Floor level under TV console or corner",
        wiring: "Standard 220V grounded electrical outlet near baseboard",
        purpose: "التنظيف الذاتي اليومي المجدول عند مغادرة أفراد المنزل والعودة التلقائية لقاعدة الشحن مع تنبيهات الصيانة.",
        technicalSpecs: "LiDAR SLAM Navigation, 5000Pa Suction, Sonic Mopping 3000rpm, 2.5L Dust Bag in Station.",
        pos3d: { x: -4.5, y: 0.15, z: 2.5 }
    }
];

const ELECTRICAL_DATA = {
    title: "البنية التحتية الكهربائية للفيلا الذكية (Smart Electrical Infrastructure)",
    subtitle: "تصميم هندسي متقدم يراعي الأمان، استقرار التغذية، والفصل المعياري لدوائر التيار الخفيف",
    panels: [
        {
            name: "اللوحة الرئيسية (Main Distribution Board - MDB)",
            location: "غرفة العدادات والخدمة الخارجية",
            specs: "3-Phase 400V, 100A Incomer, Surge Protective Device (SPD Type 1+2), Central Energy Meter.",
            role: "استقبال التغذية الرئيسية وتوزيعها على لوحات التوزيع الفرعية مع حماية الفيلا من الصواعق وتذبذب الجهد."
        },
        {
            name: "اللوحة الذكية الفرعية للطابق الأرضي (SMDB-GF)",
            location: "الممر الخدمي المجاور للمطبخ",
            specs: "Smart Circuit Breakers (RCBOs) with Modbus/RS485 Power Monitoring, Residual Current 30mA.",
            role: "تغذية دوائر الإنارة، المخارج، والمكيفات مع قياس استهلاك الطاقة لكل قاطع لحظيًا."
        },
        {
            name: "اللوحة الذكية الفرعية للطابق الأول (SMDB-1F)",
            location: "موزع الطابق الأول",
            specs: "Compact DIN-Rail Enclosure, Smart Relays for Hallway & Exterior Lighting, Dedicated Clean Line for Office.",
            role: "عزل أحمال الطابق الأول وتوفير خط كهربائي منقى (Filtered Power) لأجهزة الحواسيب والمكتب."
        },
        {
            name: "وحدة الطاقة غير المنقطعة المركزية (Central UPS 2000VA)",
            location: "غرفة التقنية وكابينة السيرفر (Tech Room)",
            specs: "Online Double-Conversion 2kVA / 1800W, Pure Sine Wave, 120-minute Backup for Low-Voltage Systems.",
            role: "تغذية مستمرة وبدون انقطاع (0ms transfer) لكابينة الشبكة، الكاميرات، بوابات الأتمتة، وأقفال الأمان."
        }
    ],
    neutralWireRequirement: {
        title: "متطلب السلك المحايد (Neutral Wire Requirement)",
        description: "تم توجيه مقاول الكهرباء بتمديد السلك المحايد (Neutral N) داخل جميع علب المفاتيح الجدارية في الفيلا بلا استثناء (بعمق 50mm على الأقل)، لضمان تزويد المفاتيح الذكية بتغذية مستقرة دائمة دون الحاجة لمكثفات توازي Bypass، وضمان استمرار عمل شبكة التكرار Mesh Network حتى عند إطفاء المصباح.",
        benefit: "استقرار تام في الإشارة وتفادي وميض مصابيح الـ LED المنخفضة القوة (Ghost Glow)."
    },
    disclaimer: "ملاحظة هندسية معتمدة: هذه الدراسة تقدم التوصيات والمتطلبات التقنية الخاصة بأنظمة المنزل الذكي والتيار الخفيف. التفاصيل التنفيذية النهائية للأحمال وحسابات مقاطع الكابلات وقواطع الحماية تخضع للتصميم الكهربائي المعتمد من مهندس كهربائي مرخص وفق الكود المعتمد محلياً (SBC / NEC / IEC)."
};

const NETWORK_DATA = {
    title: "البنية التحتية للشبكات والاتصالات (Network & Communication Architecture)",
    subtitle: "شبكة فئة المؤسسات (Enterprise-Grade) تضمن السرعة، الاستقرار، والأمن السيبراني الصارم",
    vlans: [
        { id: "VLAN 10", name: "Management & Infrastructure", subnet: "192.168.10.0/24", purpose: "إدارة الموزعات، نقاط الوصول، وجهاز الـ UPS ومنافذ الصيانة." },
        { id: "VLAN 20", name: "IoT & Smart Devices (Isolated)", subnet: "192.168.20.0/24", purpose: "أجهزة المنزل الذكي، الحساسات، والمتحكمات، معزولة بالكامل عن الإنترنت الخارجي للحماية التامة." },
        { id: "VLAN 30", name: "Surveillance & CCTV", subnet: "192.168.30.0/24", purpose: "كاميرات المراقبة بدقة 4K ووحدة التسجيل NVR، محجوبة تمامًا عن الوصول العام." },
        { id: "VLAN 40", name: "Primary Family LAN", subnet: "192.168.40.0/24", purpose: "الحواسيب، الشاشات الذكية، الهواتف الشخصية، مع أولوية قصوى لسرعة التصفح والألعاب." },
        { id: "VLAN 50", name: "Guest Network", subnet: "192.168.50.0/24", purpose: "شبكة الضيوف المعزولة ذات صلاحيات تصفح إنترنت فقط دون إمكانية رؤية أجهزة الفيلا." }
    ],
    topologyFlow: [
        { step: 1, title: "Fiber Internet ONT", desc: "مدخل الألياف البصرية بسرعة فائقة (1 Gbps)." },
        { step: 2, title: "Edge Security Router & Firewall", desc: "جدار ناري للأمن السيبراني، توجيه حركة البيانات، وتطبيق سياسات عزل الشبكات VLANs." },
        { step: 3, title: "Managed 24-Port PoE+ Core Switch", desc: "توزيع الطاقة والبيانات عبر كابلات Cat6A إلى نقاط الوصول والكاميرات وبوابات الأتمتة." },
        { step: 4, title: "Wi-Fi 6 APs & Wired Endpoints", desc: "بث شبكات Wi-Fi 6 الموزعة في أرجاء الفيلا مع تجوال سلس (Zero Handoff Roaming)." },
        { step: 5, title: "Local Edge Automation Hub", desc: "المعالج المحلي الذي يربط بين شبكة IP وبروتوكولات Zigbee/Matter المحلية." }
    ]
};

const WIRING_GUIDE = {
    title: "دليل التمديدات والمسارات السلكية (Wiring & Conduit Infrastructure)",
    principles: [
        {
            title: "فصل التيارات الكهربائية (Voltage Segregation)",
            desc: "فصل مواسير التيار الخفيف (Low Voltage Cat6A / IoT) عن مواسير التيار العالي (220V Power) بمسافة لا تقل عن 20 سم لتفادي أي تداخل كهرومغناطيسي (EMI)."
        },
        {
            title: "قياسات المواسير البلاستيكية (PVC Conduit Sizing)",
            desc: "استخدام مواسير 25mm لنقاط الشبكة والكاميرات لتسهيل سحب الكابلات مستقبلًا، ومواسير 20mm للإنارة والحساسات، مع تفادي الانحناءات الحادة (Radius > 6x Cable OD)."
        },
        {
            title: "علب التوزيع والمفاتيح (Deep Backboxes)",
            desc: "تركيب علب جدارية مربعة 86x86mm بعمق 50mm لجميع مفاتيح الإنارة لإتاحة مساحة كافية للأسلاك ووحدات التحكم الذكية دون ضغط ميكانيكي."
        },
        {
            title: "تقنية الطاقة عبر الإيثرنت (PoE Direct Home-Run)",
            desc: "تمديد كابلات الكاميرات ونقاط الوصول مباشرة (Home-Run) من كابينة الشبكة بدون أي لحامات أو نقاط ربط وسطية لضمان كفاءة وصول تيار الـ PoE."
        }
    ]
};

const SYSTEM_ARCHITECTURE = {
    title: "الهندسة البنائية وتكامل الأنظمة (4-Tier System Architecture)",
    tiers: [
        {
            level: "Tier 1: Field Devices & Sensors",
            title: "الطبقة الأولى: أجهزة الميدان والحساسات",
            desc: "المفاتيح الذكية، حساسات الحركة والدخان، الكاميرات، الأقفال، ومحركات الستائر. تتصل عبر Zigbee 3.0, Matter, أو PoE."
        },
        {
            level: "Tier 2: Edge Controllers & Local Gateways",
            title: "الطبقة الثانية: بوابات الربط والمعالجة المحلية",
            desc: "وحدة المعالجة المركزية (Local Hub)، بوابة Thread/Zigbee، وجهاز التسجيل NVR. تنفذ جميع الأوامر محليًا بأقل من 15ms زمن استجابة."
        },
        {
            level: "Tier 3: Enterprise Local Network",
            title: "الطبقة الثالثة: الشبكة المحلية المدارة",
            desc: "الموزعات المدارة، جدار الحماية، نقاط الوصول Wi-Fi 6، مع عزل أمني صارم عبر 5 شبكات افتراضية VLANs."
        },
        {
            level: "Tier 4: Interaction, UI & Optional Cloud Bridge",
            title: "الطبقة الرابعة: واجهات المستخدم والتحكم",
            desc: "الشاشات الجدارية، الهواتف الذكية، المساعدات الصوتية، مع تشفير كامل للاتصال عن بعد دون تخزين أي بيانات في خوادم خارجية غير موثوقة."
        }
    ]
};

const SIMULATION_SCENARIOS = {
    fire: {
        id: "fire",
        title: "سيناريو طوارئ الحريق (Fire Emergency Simulation)",
        location: "المطبخ الذكي (Smart Kitchen)",
        steps: [
            "حساس الدخان الكهروضوئي يكتشف انتشار الأدخنة.",
            "إطلاق صافرة الإنذار الصوتية والوميضية (110dB Strobe Siren).",
            "إيقاف وحدات التكييف (HVAC) فورًا لمنع سحب الدخان إلى غرف النوم.",
            "إضاءة مسار الهروب وأبواب الخروج باللون الأحمر التحذيري.",
            "فتح الأقفال الذكية تلقائيًا لتسهيل الإخلاء وفرق الطوارئ.",
            "إرسال إشعار طارئ فوري لجميع شاشات وهواتف أفراد المنزل."
        ]
    },
    fridge: {
        id: "fridge",
        title: "محاكاة الثلاجة الذكية ومخزون الأغذية (Smart Refrigerator)",
        parameters: {
            temp: 4.0,
            foodLevel: 78,
            door: "Closed"
        }
    },
    vacuum: {
        id: "vacuum",
        title: "محاكاة المكنسة الروبوتية (Robot Vacuum & Mop)",
        parameters: {
            battery: 85,
            dustContainer: 25,
            waterTank: 90,
            status: "Docked"
        }
    },
    intrusion: {
        id: "intrusion",
        title: "سيناريو محاولة التسلل الأمني (Security Perimeter Breach)",
        steps: [
            "حساس السور الخارجي أو نافذة الصالة يستشعر فتحًا غير مصرح به.",
            "كاميرا المراقبة 4K تلتقط لقطة واضحة وتوجه الإضاءة الكاشفة للهدف.",
            "إطلاق تنبيه أمني وإرسال صورة فورية للهاتف مع بث الفيديو المباشر.",
            "قفل جميع الأبواب الداخلية لمنع الوصول إلى مناطق النوم."
        ]
    },
    waterLeak: {
        id: "waterLeak",
        title: "سيناريو تسرب المياه (Water Leak Emergency)",
        steps: [
            "حساس تسرب المياه تحت حوض المطبخ يلامس قطرات متسربة.",
            "المحبس الكهرومغناطيسي يغلق خط التغذية الرئيسي للمياه خلال ثانيتين.",
            "إيقاف تشغيل غسالة الصحون والغسالة الذكية.",
            "إشعار فوري: تم إغلاق المياه بنجاح ومنع حدوث أضرار في الأرضيات."
        ]
    }
};

const FULL_DAY_SCHEDULE = [
    {
        time: "07:00",
        label: "صباح مشرق (Good Morning)",
        sunElevation: 15,
        sunIntensity: 0.6,
        ambientColor: "#fde68a",
        skyColor: "#bfdbfe",
        lightsState: { living: 0, majlis: 0, master_bed: 60, kitchen: 80, garden: 0 },
        acState: "Comfort (22°C)",
        desc: "تبدأ الستائر بالفتح تدريجيًا لمحاكاة الشروق الطبيعي، ترتفع حرارة الغرفة إلى 23°C، وتضاء إنارة المطبخ لتحضير القهوة والإفطار.",
        notification: "🌅 سيناريو الصباح: فُتحت الستائر، وبدأ تحضير المطبخ."
    },
    {
        time: "08:30",
        label: "مغادرة الفيلا للعمل (Leaving Home)",
        sunElevation: 45,
        sunIntensity: 1.0,
        ambientColor: "#ffffff",
        skyColor: "#93c5fd",
        lightsState: { living: 0, majlis: 0, master_bed: 0, kitchen: 0, garden: 0 },
        acState: "ECO Mode (25°C)",
        desc: "جميع أفراد العائلة غادروا الفيلا. إطفاء كامل للمصابيح، تحويل التكييف لوضع توفير الطاقة (ECO)، قفل الباب الرئيسي، وتفعيل نظام الحماية الأمني.",
        notification: "🔒 سيناريو المغادرة: تم قفل الأبواب، تفعيل الحراسة، والتكييف في وضع التوفير."
    },
    {
        time: "12:30",
        label: "ذروة النهار والتنظيف الذكي (Solar & Cleaning)",
        sunElevation: 85,
        sunIntensity: 1.2,
        ambientColor: "#ffffff",
        skyColor: "#60a5fa",
        lightsState: { living: 0, majlis: 0, master_bed: 0, kitchen: 0, garden: 0 },
        acState: "ECO Mode (25°C)",
        desc: "أعلى إنتاجية للمنظومة الشمسية المتوقعة. تبدأ المكنسة الروبوتية دورة تنظيف الصالة والمجلس تلقائيًا، وإغلاق الستائر لتقليل الحمل الحراري للزجاج.",
        notification: "🤖 بدأت المكنسة الروبوتية تنظيف الصالة والمجلس في فترة خلو المنزل."
    },
    {
        time: "17:30",
        label: "عودة العائلة والترحيب (Family Return)",
        sunElevation: 10,
        sunIntensity: 0.7,
        ambientColor: "#fed7aa",
        skyColor: "#fdba74",
        lightsState: { living: 80, majlis: 0, master_bed: 0, kitchen: 90, garden: 60 },
        acState: "Comfort (21.5°C)",
        desc: "استشعار اقتراب السيارة: إضاءة المدخل والممر الخارجي، تبريد مسبق للصالة، فتح الستائر، وتشغيل إضاءة الحديقة الهادئة مع غروب الشمس.",
        notification: "🏡 سيناريو الترحيب: مرحبًا بعودتكم! تم ضبط التكييف والإنارة الدافئة."
    },
    {
        time: "22:30",
        label: "وضع النوم والسكينة (Night Mode)",
        sunElevation: -40,
        sunIntensity: 0.1,
        ambientColor: "#1e1b4b",
        skyColor: "#0f172a",
        lightsState: { living: 0, majlis: 0, master_bed: 20, kitchen: 0, garden: 20 },
        acState: "Night Silent (21.0°C)",
        desc: "تفعيل وضع السكينة الليلي بلمسة زر Master-Off بجانب السرير. إطفاء إنارة الفيلا، تفعيل الحساسات المحيطية، وإبقاء إضاءة حمام الماستر خافتة 10%.",
        notification: "🌙 وضع السكون: أُطفئت الإنارة العامة، وفُعّلت الحماية المحيطية الخارجية."
    },
    {
        time: "02:15",
        label: "الحراسة المحيطية الليلية (Perimeter Guard)",
        sunElevation: -70,
        sunIntensity: 0.05,
        ambientColor: "#090d16",
        skyColor: "#020617",
        lightsState: { living: 0, majlis: 0, master_bed: 0, kitchen: 0, garden: 15 },
        acState: "Night Silent (21.0°C)",
        desc: "هدوء تام في الفيلا. تعمل الكاميرات برؤيتها الليلية بالأشعة تحت الحمراء، والأنظمة في أعلى جاهزية لكشف أي حركة غير طبيعية في المحيط الخارجي.",
        notification: "🛡️ الفحص الأمني التلقائي: جميع الأجهزة مؤمنة بنجاح، ولا توجد أي اختراقات."
    }
];

const BILL_OF_MATERIALS = [
    {
        id: "BOM-001",
        item: "مفتاح ذكي مزدوج (Smart 2-Gang Switch)",
        image: "assets/devices/smart-switch-2gang.svg",
        category: "Lighting",
        categoryAr: "الإضاءة",
        room: "Entrance & Hallways",
        roomAr: "المداخل والممرات",
        qty: 8,
        unit: "قطعة",
        protocol: "Zigbee 3.0 / Matter",
        power: "220V AC + Neutral",
        unitPriceSAR: 220,
        totalPriceSAR: 1760,
        wiringNote: "علبة مربعة عميقة 50mm مع تمديد سلك محايد (Neutral)."
    },
    {
        id: "BOM-002",
        item: "مخفت إضاءة ذكي (Smart Rotary/Touch Dimmer)",
        image: "assets/devices/smart-dimmer.svg",
        category: "Lighting",
        categoryAr: "الإضاءة",
        room: "Living, Majlis, Master Bed",
        roomAr: "الصالة، المجلس، الماستر",
        qty: 6,
        unit: "قطعة",
        protocol: "Matter over Thread",
        power: "220V AC Phase-Cut",
        unitPriceSAR: 280,
        totalPriceSAR: 1680,
        wiringNote: "متوافق مع محركات LED القابلة للتعتيم (Dimmable Drivers)."
    },
    {
        id: "BOM-003",
        item: "مرحل ذكي باللوحة (DIN-Rail Smart Relay 4-Ch)",
        image: "assets/devices/din-relay.svg",
        category: "Lighting",
        categoryAr: "الإضاءة",
        room: "Sub-Distribution Panels",
        roomAr: "لوحات التوزيع الفرعية",
        qty: 4,
        unit: "وحدة",
        protocol: "Zigbee / Modbus RS485",
        power: "220V AC DIN-Rail",
        unitPriceSAR: 450,
        totalPriceSAR: 1800,
        wiringNote: "تركيب داخل اللوحة الفرعية على مسار DIN-Rail قياسي."
    },
    {
        id: "BOM-004",
        item: "حساس حركة ووجود بشري راداري (mmWave Sensor)",
        image: "assets/devices/mmwave-sensor.svg",
        category: "Sensors",
        categoryAr: "الحساسات",
        room: "All Rooms & Bathrooms",
        roomAr: "جميع الغرف والحمامات",
        qty: 12,
        unit: "قطعة",
        protocol: "Zigbee 3.0",
        power: "5V DC USB / 220V Concealed",
        unitPriceSAR: 180,
        totalPriceSAR: 2160,
        wiringNote: "تغذية مستمرة في سقف الجبس مع كابلين 0.75mm²."
    },
    {
        id: "BOM-005",
        item: "حساس مغناطيسي مخفي للأبواب والنوافذ",
        image: "assets/devices/door-sensor.svg",
        category: "Sensors",
        categoryAr: "الحساسات",
        room: "Exterior Doors & Ground Windows",
        roomAr: "الأبواب الخارجية والنوافذ",
        qty: 10,
        unit: "قطعة",
        protocol: "Zigbee 3.0",
        power: "CR2032 Lithium Battery",
        unitPriceSAR: 95,
        totalPriceSAR: 950,
        wiringNote: "تركيب مخفي تجويفي داخل إطار الألمنيوم أو الخشب."
    },
    {
        id: "BOM-006",
        item: "حساس دخان وحرارة كهروضوئي معتمد",
        image: "assets/devices/smoke-detector.svg",
        category: "Sensors",
        categoryAr: "الحساسات",
        room: "Kitchen, Hallways, Tech Room",
        roomAr: "المطبخ، الممرات، التقنية",
        qty: 6,
        unit: "قطعة",
        protocol: "Zigbee 3.0 + Interlink",
        power: "10-Yr Battery + Hardwired",
        unitPriceSAR: 240,
        totalPriceSAR: 1440,
        wiringNote: "سلك ربط Interconnect بين جميع الحساسات لإطلاق صافرة موحدة."
    },
    {
        id: "BOM-007",
        item: "حساس تسرب مياه مع محبس كهرومغناطيسي 1 بوصة",
        image: "assets/devices/water-leak-valve.svg",
        category: "Sensors",
        categoryAr: "الحساسات",
        room: "Kitchen & Master Bathroom",
        roomAr: "المطبخ والحمام الرئيسي",
        qty: 2,
        unit: "طقم",
        protocol: "Zigbee 3.0 Direct Binding",
        power: "12V DC Adapter for Valve",
        unitPriceSAR: 550,
        totalPriceSAR: 1100,
        wiringNote: "تركيب المحبس على خط التغذية الميكانيكي مع تيار 12V."
    },
    {
        id: "BOM-008",
        item: "حساس كشف تسرب الغاز (Combustible Gas)",
        image: "assets/devices/gas-detector.svg",
        category: "Sensors",
        categoryAr: "الحساسات",
        room: "Kitchen",
        roomAr: "المطبخ",
        qty: 1,
        unit: "قطعة",
        protocol: "Zigbee 3.0 + Dry Contact",
        power: "220V AC Direct Feed",
        unitPriceSAR: 260,
        totalPriceSAR: 260,
        wiringNote: "سلك إشارة إلى شفاط الطوارئ ومحبس الغاز الخارجي."
    },
    {
        id: "BOM-009",
        item: "قفل ذكي بيومتري عالي الأمان مع مقبض نقر",
        image: "assets/devices/smart-lock.svg",
        category: "Security",
        categoryAr: "الأمن والتحكم",
        room: "Main Entrance",
        roomAr: "المدخل الرئيسي",
        qty: 1,
        unit: "طقم",
        protocol: "Zigbee 3.0 / Matter",
        power: "Rechargeable Lithium + Backup",
        unitPriceSAR: 1450,
        totalPriceSAR: 1450,
        wiringNote: "تجهيز فراغ المورتيز 6068 في الباب الخارجي وتمديد سلك مفصلة اختياري."
    },
    {
        id: "BOM-010",
        item: "جرس باب ذكي بكاميرا 2K ومكالمة ثنائية الاتجاه",
        image: "assets/devices/video-doorbell.svg",
        category: "Security",
        categoryAr: "الأمن والتحكم",
        room: "Entrance Door",
        roomAr: "بوابة المدخل",
        qty: 1,
        unit: "قطعة",
        protocol: "Wi-Fi 6 / RTSP Stream",
        power: "16-24V AC Hardwired",
        unitPriceSAR: 750,
        totalPriceSAR: 750,
        wiringNote: "ماسورة 25mm PVC مع كابل Cat6A ومحول 16V AC داخل اللوحة."
    },
    {
        id: "BOM-011",
        item: "كاميرا مراقبة خارجية 4K PoE مع ذكاء اصطناعي",
        image: "assets/devices/bullet-camera.svg",
        category: "Security",
        categoryAr: "الأمن والتحكم",
        room: "Perimeter & Garden & Garage",
        roomAr: "المحيط الخارجي والمرآب",
        qty: 6,
        unit: "قطعة",
        protocol: "PoE IEEE 802.3af (Cat6A)",
        power: "PoE 48V (8W Max)",
        unitPriceSAR: 680,
        totalPriceSAR: 4080,
        wiringNote: "كابل خارجي محمي Cat6A FTP في مواسير UV-proof مباشرة إلى الراك."
    },
    {
        id: "BOM-012",
        item: "منظم حرارة ذكي بشاشة زجاجية (Smart Thermostat)",
        image: "assets/devices/smart-thermostat.svg",
        category: "HVAC",
        categoryAr: "التكييف والمناخ",
        room: "Living, Majlis, Bedrooms, Office",
        roomAr: "الصالة، المجلس، الغرف، المكتب",
        qty: 6,
        unit: "قطعة",
        protocol: "Zigbee 3.0 / Modbus RTU",
        power: "24V AC C-Wire",
        unitPriceSAR: 480,
        totalPriceSAR: 2880,
        wiringNote: "كابل تحكم خماسي محمي 5-Core إلى وحدة التكييف المخفية في السقف."
    },
    {
        id: "BOM-013",
        item: "كابينة شبكة 19 بوصة 12U مع ملحقاتها",
        image: "assets/devices/network-rack.svg",
        category: "Network",
        categoryAr: "الشبكات والاتصالات",
        room: "Tech Room",
        roomAr: "غرفة التقنية",
        qty: 1,
        unit: "مجموعة",
        protocol: "Physical Standard Rack",
        power: "220V AC PDU",
        unitPriceSAR: 1200,
        totalPriceSAR: 1200,
        wiringNote: "تثبيت جداري ببراغي ثقيلة وتأريض نحاسي نظيف مباشر للأرضي."
    },
    {
        id: "BOM-014",
        item: "موزع شبكة 24-Port Gigabit PoE+ مُدار (370W)",
        image: "assets/devices/poe-switch.svg",
        category: "Network",
        categoryAr: "الشبكات والاتصالات",
        room: "Tech Room (Rack U4)",
        roomAr: "غرفة التقنية",
        qty: 1,
        unit: "جهاز",
        protocol: "L2+ Managed / VLAN Support",
        power: "220V AC Internal",
        unitPriceSAR: 2300,
        totalPriceSAR: 2300,
        wiringNote: "ربط عبر كابلات Patch Cords Cat6A مع Patch Panel 24-Port."
    },
    {
        id: "BOM-015",
        item: "نقطة وصول لاسلكية Wi-Fi 6 سقفية فئة مؤسسات",
        image: "assets/devices/wifi6-ap.svg",
        category: "Network",
        categoryAr: "الشبكات والاتصالات",
        room: "Ground & First Floor Ceilings",
        roomAr: "أسقف الطابقين الأرضي والأول",
        qty: 4,
        unit: "قطعة",
        protocol: "Wi-Fi 6 Dual Band 4x4",
        power: "PoE+ (802.3at - 12W)",
        unitPriceSAR: 650,
        totalPriceSAR: 2600,
        wiringNote: "كابل مباشر Cat6A PoE في سقف الجبس مع حلقة صيانة بطول 1.5م."
    },
    {
        id: "BOM-016",
        item: "جهاز تسجيل فيديو شبكي 8-Ch 4K NVR مع 12TB تخزين",
        image: "assets/devices/nvr-recorder.svg",
        category: "Network",
        categoryAr: "الشبكات والاتصالات",
        room: "Tech Room (Rack U6)",
        roomAr: "غرفة التقنية",
        qty: 1,
        unit: "طقم",
        protocol: "Gigabit Ethernet IP",
        power: "220V AC via UPS",
        unitPriceSAR: 2800,
        totalPriceSAR: 2800,
        wiringNote: "قرصي تخزين 2x 6TB فئة مراقبة متواصلة WD Purple."
    },
    {
        id: "BOM-017",
        item: "المعالج المركزي للأتمتة المحلية (Edge Smart Hub)",
        image: "assets/devices/edge-hub.svg",
        category: "Automation",
        categoryAr: "وحدات التحكم المركزية",
        room: "Tech Room (Rack U2)",
        roomAr: "غرفة التقنية",
        qty: 1,
        unit: "جهاز",
        protocol: "Matter, Thread, Zigbee 3.0, LAN",
        power: "12V DC via UPS",
        unitPriceSAR: 1950,
        totalPriceSAR: 1950,
        wiringNote: "اتصال إيثرنت محلي عالي الاستقرار + هوائيات خارجية معززة."
    },
    {
        id: "BOM-018",
        item: "وحدة طاقة احتياطية ذكية (Online UPS 2000VA)",
        image: "assets/devices/online-ups.svg",
        category: "Electrical",
        categoryAr: "البنية الكهربائية",
        room: "Tech Room (Rack Base)",
        roomAr: "غرفة التقنية",
        qty: 1,
        unit: "جهاز",
        protocol: "Pure Sine Wave, SNMP Card",
        power: "2kVA / 1800W Battery",
        unitPriceSAR: 3200,
        totalPriceSAR: 3200,
        wiringNote: "قاطع تغذية مستقل 20A من اللوحة الفرعية مع تبريد مستمر."
    }
];
